// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrrpqjH5Rsmp_wh4CM6ZIDWj_lKZ-Nn3s',
    appId: '1:828874697813:web:6eac761c7552a69bb778dc',
    messagingSenderId: '828874697813',
    projectId: 'travelling-25896',
    authDomain: 'travelling-25896.firebaseapp.com',
    storageBucket: 'travelling-25896.appspot.com',
    measurementId: 'G-G1N1RWZS25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjmtCM0SUlCABsNsnHBgpHJw0HPSTTSIw',
    appId: '1:828874697813:android:de5d05d663c32c3bb778dc',
    messagingSenderId: '828874697813',
    projectId: 'travelling-25896',
    storageBucket: 'travelling-25896.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn2hTmuD2AJFs0YqxJoXNJciMfono7s_4',
    appId: '1:828874697813:ios:e43b67a85f6ad1f1b778dc',
    messagingSenderId: '828874697813',
    projectId: 'travelling-25896',
    storageBucket: 'travelling-25896.appspot.com',
    iosClientId: '828874697813-s09nofi8uj87mrjbedrqo2e3foqpb45l.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelling',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn2hTmuD2AJFs0YqxJoXNJciMfono7s_4',
    appId: '1:828874697813:ios:e43b67a85f6ad1f1b778dc',
    messagingSenderId: '828874697813',
    projectId: 'travelling-25896',
    storageBucket: 'travelling-25896.appspot.com',
    iosClientId: '828874697813-s09nofi8uj87mrjbedrqo2e3foqpb45l.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelling',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrrpqjH5Rsmp_wh4CM6ZIDWj_lKZ-Nn3s',
    appId: '1:828874697813:web:9a5bc568940cfbeab778dc',
    messagingSenderId: '828874697813',
    projectId: 'travelling-25896',
    authDomain: 'travelling-25896.firebaseapp.com',
    storageBucket: 'travelling-25896.appspot.com',
    measurementId: 'G-EZ24JQBWXN',
  );

}